//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandAuto
{
    using System;
    using System.Collections.Generic;

    public partial class CarroOficina : Carro
    {
        public string Matricula { get; set; }
        public string Kms { get; set; }
        public int ClienteIdCliente { get; set; }
        public virtual ICollection<Serviço> Serviço { get; set; } 
        public virtual Cliente Cliente { get; set; }

        public override string ToString()
        {
            return IdCarro + " " + Matricula + " - " + Kms + "KMS"; 
        }
    }
}
