//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serviço
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Serviço()
        {
            this.Parcela = new HashSet<Parcela>();
        }
    
        public int IdServicos { get; set; }
        public string DataEntrada { get; set; }
        public string Tipo { get; set; }
        public string DtaSaida { get; set; }
        public string CarroOficinaIdCliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcela> Parcela { get; set; }
    }
}
